### ISSUE TITLE
"Generate syntax" button in Anki times out, crashes, with latest browser extension

### ISSUE THREAD

**Issue by saxoncameron** [migaku-official/migaku-browser-extension-issue-tracker#24]
## Description

When attempting to press the "Generate Syntax" 文 button in Anki's card browser or card edit window on an "Expression" field, it hangs for a few seconds then says "Request timed out".
![image](https://user-images.githubusercontent.com/3240185/153534870-7989a33c-8f10-44a5-a312-a199b29bf2eb.png)

## Error report

I'm not getting this same error report any more, just the timeout dialog, but the first time I came across this issue, Anki crashed and gave me this error report:

```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-02-11 14:30:51
Add-ons possibly involved: ⁨Migaku Anki Extension⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/taskman.py", line 101, in _on_closures_pending
  File "/Users/saxoncameron/Library/Application Support/Anki2/addons21/Migaku Anki Extension/migaku_connection/__init__.py", line 106, in <lambda>
    lambda: func(*args, **kwargs)
  File "/Users/saxoncameron/Library/Application Support/Anki2/addons21/Migaku Anki Extension/editor.py", line 55, in <lambda>
    on_error = lambda msg: util.show_critical(msg, parent=editor.parentWindow),
  File "/Users/saxoncameron/Library/Application Support/Anki2/addons21/Migaku Anki Extension/util.py", line 64, in show_critical
    return show_msg_box(text, title, parent, QMessageBox.Critical)
  File "/Users/saxoncameron/Library/Application Support/Anki2/addons21/Migaku Anki Extension/util.py", line 76, in show_msg_box
    mb = QMessageBox(parent)
RuntimeError: wrapped C/C++ object of type EditCurrent has been deleted

```

## Screenshots

![Pasted_Image_11_2_2022__2_51_pm](https://user-images.githubusercontent.com/3240185/153534997-b57fa77a-35c5-4a7a-a7aa-50b9e9ece418.png)

## Versions

- OS: macOS Monterey 12.1; MacBook Pro 16" 2019
- Browser extension v0.9.3.2
- Both Anki addons `v0.1.0-alpha.12` and `v0.1.0-alpha.13`

**Comment by saxoncameron** [comment]
Not sure if this helps, but here's the above Anki card in question

[Uploading Anki card.apkg.zip…]()

**Comment by saxoncameron** [comment]
Can confirm this issue persists with Anki addon `v0.1.0-alpha.13` as well.

**Comment by LucasMIA** [comment]
Has been fixed.
